openapi: 3.0.1
info:
  title: Shopping list plugin
  description: Use this plugin to retrieve the shopping list and store layout, which you then will use to help the user find and purchase the products.
  version: 'v1'
servers:
  - url: https://shoppingassistantchatgptplugin.vovakhromakov.repl.co
paths:
  /getShoppingListAndStoreLayout:
    get:
      operationId: getShoppingListAndStoreLayout
      summary: Get the shopping list and a description of the store layout
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getShoppingListAndStoreLayoutResponse'
components:
  schemas:
    getShoppingListAndStoreLayoutResponse:
      type: object
      properties:
        shoppingList:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the item on the shopping list
              isPurchased:
                type: boolean
                description: Whether the item has been purchased or not, please disregard purchased products, and do not mention them to the user.
            required:
              - name
              - isPurchased
          description: The items on the shopping list
        storeLayout:
          type: string
          description: A description of the store layout


